import { Application, ApplicationStatus, ApplicationType, Complaint, RegistryRecord, Role, User } from '../types';

// Helper to generate a date relative to today for mock data consistency
const getRelativeDate = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

const MALE_AVATAR = 'https://dev2.phoenix.com.ph/wp-content/uploads/2026/01/portrait-happy-smiling-senior-man-260nw-2461189135.jpg';
const FEMALE_AVATAR = 'https://dev2.phoenix.com.ph/wp-content/uploads/2026/01/istockphoto-1329844196-612x612-1.jpg';

export const INITIAL_USERS: User[] = [
  {
    id: 'u_teresa',
    name: 'Teresa Magbanua',
    firstName: 'Teresa',
    lastName: 'Magbanua',
    middleName: 'Ferraris',
    suffix: '',
    role: Role.CITIZEN,
    email: 'teresa.m@email.com',
    birthDate: '1950-10-13',
    birthPlace: 'Pototan, Iloilo',
    sex: 'Female',
    civilStatus: 'Married',
    citizenship: 'Filipino',
    address: '123 G. Aglipay St, San Juan',
    seniorIdNumber: 'SC-2021-777',
    seniorIdIssueDate: '2021-03-20',
    seniorIdExpiryDate: getRelativeDate(45),
    avatarUrl: FEMALE_AVATAR,
    contactNumber: '0917 777 8888',
    username: 'teresa',
    password: 'asd',
    livingArrangement: 'Owned',
    isPensioner: true,
    pensionAmount: '8,000',
    pensionSource: 'SSS'
  },
  {
    id: 'u_dummy',
    name: 'Juan Dela Cruz',
    firstName: 'Juan',
    lastName: 'Dela Cruz',
    middleName: 'Santos',
    suffix: 'Jr.',
    role: Role.CITIZEN,
    email: 'juan@email.com',
    birthDate: '1955-03-15',
    birthPlace: 'San Juan City',
    sex: 'Male',
    civilStatus: 'Married',
    citizenship: 'Filipino',
    address: '155 F. Blumentritt, San Juan',
    seniorIdNumber: 'SC-2024-DUMMY',
    seniorIdIssueDate: '2024-01-15',
    seniorIdExpiryDate: '2027-01-15',
    avatarUrl: MALE_AVATAR,
    contactNumber: '0917 000 0000',
    emergencyContact: 'Maria Dela Cruz - 0917 111 1111',
    emergencyContactPerson: 'Maria Dela Cruz',
    emergencyContactNumber: '0917 111 1111',
    username: 'juan',
    password: 'asd',
    livingArrangement: 'Owned',
    isPensioner: true,
    pensionAmount: '5,000',
    pensionSource: 'SSS',
    hasIllness: true,
    illnessDetails: 'Hypertension',
    bloodType: 'O+',
    joinFederation: true
  },
  {
    id: 'u_luz',
    name: 'Luzviminda Dimagiba',
    firstName: 'Luzviminda',
    lastName: 'Dimagiba',
    middleName: 'Perez',
    suffix: '',
    role: Role.CITIZEN,
    email: 'luz.dimagiba@email.com',
    birthDate: '1952-08-20',
    birthPlace: 'San Juan City',
    sex: 'Female',
    civilStatus: 'Widowed',
    citizenship: 'Filipino',
    address: '99 N. Domingo St, San Juan',
    seniorIdNumber: 'SC-2020-099',
    seniorIdIssueDate: '2020-09-10',
    seniorIdExpiryDate: '2023-09-10',
    avatarUrl: FEMALE_AVATAR,
    contactNumber: '0917 999 0011',
    username: 'luz',
    password: 'asd',
    livingArrangement: 'Owned',
    isPensioner: true,
    pensionAmount: '6,500',
    pensionSource: 'SSS'
  },
  {
    id: 'a1',
    name: 'Admin Officer',
    role: Role.ADMIN,
    email: 'admin@gov.ph',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    username: 'admin',
    password: 'asd'
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app_m1',
    userId: 'm1',
    userName: 'TERESA MAGBANUA',
    type: ApplicationType.REGISTRATION,
    date: '2021-03-15',
    status: ApplicationStatus.APPROVED,
    description: 'Initial migration record',
    formData: {
      firstName: 'TERESA',
      lastName: 'MAGBANUA',
      middleName: 'FERRARIS',
      suffix: '',
      birthDate: '1950-10-13',
      birthPlace: 'POTOTAN, ILOILO',
      sex: 'FEMALE',
      citizenship: 'FILIPINO',
      civilStatus: 'MARRIED',
      address: '123 G. AGLIPAY ST, SAN JUAN',
      houseNo: '123',
      street: 'G. AGLIPAY ST',
      barangay: 'ADDITION HILLS',
      district: '1ST DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09177778888',
      scid_number: 'SCID-000001',
      emergencyContactPerson: 'N/A',
      emergencyContactNumber: 'N/A',
      joinFederation: true
    }
  },
  {
    id: 'app_m2',
    userId: 'm2',
    userName: 'JUAN DELA CRUZ',
    type: ApplicationType.REGISTRATION,
    date: '2024-01-10',
    status: ApplicationStatus.APPROVED,
    description: 'Initial migration record',
    formData: {
      firstName: 'JUAN',
      lastName: 'DELA CRUZ',
      middleName: 'SANTOS',
      suffix: 'JR.',
      birthDate: '1955-03-15',
      birthPlace: 'SAN JUAN CITY',
      sex: 'MALE',
      citizenship: 'FILIPINO',
      civilStatus: 'MARRIED',
      address: '155 F. BLUMENTRITT, SAN JUAN',
      houseNo: '155',
      street: 'F. BLUMENTRITT',
      barangay: 'BATIS',
      district: '1ST DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09170000000',
      scid_number: 'SCID-000002',
      emergencyContactPerson: 'MARIA DELA CRUZ',
      emergencyContactNumber: '09171111111',
      joinFederation: true
    }
  },
  {
    id: 'app_m3',
    userId: 'm3',
    userName: 'LUZVIMINDA DIMAGIBA',
    type: ApplicationType.REGISTRATION,
    date: '2020-09-05',
    status: ApplicationStatus.APPROVED,
    description: 'Initial migration record',
    formData: {
      firstName: 'LUZVIMINDA',
      lastName: 'DIMAGIBA',
      middleName: 'PEREZ',
      suffix: '',
      birthDate: '1952-08-20',
      birthPlace: 'SAN JUAN CITY',
      sex: 'FEMALE',
      citizenship: 'FILIPINO',
      civilStatus: 'WIDOWED',
      address: '99 N. DOMINGO ST, SAN JUAN',
      houseNo: '99',
      street: 'N. DOMINGO ST',
      barangay: 'CORAZON DE JESUS',
      district: '1ST DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09179990011',
      scid_number: 'SCID-000003',
      emergencyContactPerson: 'N/A',
      emergencyContactNumber: 'N/A',
      joinFederation: true
    }
  },
  {
    id: 'app_m6',
    userId: 'm6',
    userName: 'EDDIE GARCIA',
    type: ApplicationType.REGISTRATION,
    date: '2020-05-02',
    status: ApplicationStatus.APPROVED,
    description: 'Initial migration record',
    formData: {
      firstName: 'EDDIE',
      lastName: 'GARCIA',
      middleName: 'P',
      suffix: '',
      birthDate: '1929-05-02',
      birthPlace: 'SAN JUAN CITY',
      sex: 'MALE',
      citizenship: 'FILIPINO',
      civilStatus: 'WIDOWED',
      address: '789 SUNSET BLVD, SAN JUAN',
      houseNo: '789',
      street: 'SUNSET BLVD',
      barangay: 'ISABELITA',
      district: '1ST DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09171112222',
      scid_number: 'SCID-000005',
      emergencyContactPerson: 'N/A',
      emergencyContactNumber: 'N/A',
      joinFederation: true
    }
  },
  {
    id: 'app_m4',
    userId: 'm4',
    userName: 'RICARDO DALISAY',
    type: ApplicationType.REGISTRATION,
    date: '2026-02-20',
    status: ApplicationStatus.PENDING,
    description: 'Walk-in Enrollment. Data sourced from registry and verified by admin on-site.',
    formData: {
      firstName: 'RICARDO',
      middleName: 'A',
      lastName: 'DALISAY',
      suffix: '',
      birthDate: '1958-05-20',
      birthPlace: 'SAN JUAN CITY',
      sex: 'MALE',
      citizenship: 'FILIPINO',
      civilStatus: 'MARRIED',
      address: '123 MAIN ST, SAN JUAN',
      houseNo: '123',
      street: 'MAIN ST',
      barangay: 'ERMITAÑO',
      district: '1ST DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09171234567',
      emergencyContactPerson: 'CARDO DALISAY',
      emergencyContactNumber: '09177654321',
      joinFederation: true
    }
  },
  {
    id: 'app_m5',
    userId: 'm5',
    userName: 'NORA AUNOR',
    type: ApplicationType.REGISTRATION,
    date: '2026-02-21',
    status: ApplicationStatus.PENDING,
    description: 'Walk-in Enrollment. Data sourced from registry and verified by admin on-site.',
    formData: {
      firstName: 'NORA',
      middleName: 'V',
      lastName: 'AUNOR',
      suffix: '',
      birthDate: '1953-05-21',
      birthPlace: 'SAN JUAN CITY',
      sex: 'FEMALE',
      citizenship: 'FILIPINO',
      civilStatus: 'SINGLE',
      address: '456 BROADWAY, SAN JUAN',
      houseNo: '456',
      street: 'BROADWAY',
      barangay: 'GREENHILLS',
      district: '2ND DISTRICT',
      city: 'SAN JUAN CITY',
      province: 'METRO MANILA',
      contactNumber: '09171112222',
      emergencyContactPerson: 'NORA V',
      emergencyContactNumber: '09173334444',
      joinFederation: false
    }
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'c1',
    userId: 'u_dummy',
    userName: 'Juan Dela Cruz',
    date: '2023-10-15',
    subject: 'Delayed Pension',
    details: 'I have not received my social pension for the last 2 months.',
    status: 'Open',
  },
];

export const INITIAL_MASTERLIST_RECORDS: any[] = [
  {
    id: 'm1',
    fullName: 'MAGBANUA, TERESA FERRARIS',
    firstName: 'TERESA',
    lastName: 'MAGBANUA',
    middleName: 'FERRARIS',
    birthDate: '1950-10-13',
    birthPlace: 'POTOTAN, ILOILO',
    seniorIdNumber: 'SCID-000001',
    scid_number: 'SCID-000001',
    id_status: 'New',
    address: '123 G. AGLIPAY ST, BRGY. ADDITION HILLS, SAN JUAN CITY',
    house_no: '123',
    street: 'G. AGLIPAY ST',
    barangay: 'ADDITION HILLS',
    city_municipality: 'SAN JUAN CITY',
    province: 'METRO MANILA',
    district: '1ST DISTRICT',
    email: 'teresa.m@email.com',
    contact_number: '09177778888',
    sex: 'FEMALE',
    civilStatus: 'MARRIED'
  },
  {
    id: 'm2',
    fullName: 'DELA CRUZ, JUAN SANTOS',
    firstName: 'JUAN',
    lastName: 'DELA CRUZ',
    middleName: 'SANTOS',
    birthDate: '1955-03-15',
    birthPlace: 'SAN JUAN CITY',
    seniorIdNumber: 'SCID-000002',
    scid_number: 'SCID-000002',
    id_status: 'New',
    address: '155 F. BLUMENTRITT, BRGY. BATIS, SAN JUAN CITY',
    house_no: '155',
    street: 'F. BLUMENTRITT',
    barangay: 'BATIS',
    city_municipality: 'SAN JUAN CITY',
    province: 'METRO MANILA',
    district: '1ST DISTRICT',
    email: 'juan@email.com',
    contact_number: '09170000000',
    sex: 'MALE',
    civilStatus: 'MARRIED'
  },
  {
    id: 'm3',
    fullName: 'DIMAGIBA, LUZVIMINDA PEREZ',
    firstName: 'LUZVIMINDA',
    lastName: 'DIMAGIBA',
    middleName: 'PEREZ',
    birthDate: '1952-08-20',
    birthPlace: 'SAN JUAN CITY',
    seniorIdNumber: 'SCID-000003',
    scid_number: 'SCID-000003',
    id_status: 'New',
    address: '99 N. DOMINGO ST, BRGY. CORAZON DE JESUS, SAN JUAN CITY',
    house_no: '99',
    street: 'N. DOMINGO ST',
    barangay: 'CORAZON DE JESUS',
    city_municipality: 'SAN JUAN CITY',
    province: 'METRO MANILA',
    district: '1ST DISTRICT',
    email: 'luz.dimagiba@email.com',
    contact_number: '09179990011',
    sex: 'FEMALE',
    civilStatus: 'WIDOWED'
  },
  {
    id: 'm6',
    fullName: 'GARCIA, EDDIE P',
    firstName: 'EDDIE',
    lastName: 'GARCIA',
    middleName: 'P',
    birthDate: '1929-05-02',
    birthPlace: 'SAN JUAN CITY',
    seniorIdNumber: 'SCID-000005',
    scid_number: 'SCID-000005',
    id_status: 'New',
    address: '789 SUNSET BLVD, BRGY. ISABELITA, SAN JUAN CITY',
    house_no: '789',
    street: 'SUNSET BLVD',
    barangay: 'ISABELITA',
    city_municipality: 'SAN JUAN CITY',
    province: 'METRO MANILA',
    district: '1ST DISTRICT',
    email: 'eddie.g@email.com',
    contact_number: '09171112222',
    sex: 'MALE',
    civilStatus: 'WIDOWED'
  }
];

export const INITIAL_REGISTRY_RECORDS: RegistryRecord[] = [
  {
    id: 'r1',
    type: 'LCR',
    firstName: 'RICARDO',
    lastName: 'DALISAY',
    middleName: 'A',
    birthDate: '1958-05-20',
    sex: 'MALE',
    address: '123 MAIN ST, SAN JUAN',
    status: 'Verified',
    isRegistered: true,
    houseNo: '123',
    street: 'MAIN ST',
    barangay: 'ERMITAÑO',
    district: '1ST DISTRICT',
    city: 'SAN JUAN CITY',
    province: 'METRO MANILA'
  },
  {
    id: 'r2',
    type: 'LCR',
    firstName: 'NORA',
    lastName: 'AUNOR',
    middleName: 'V',
    birthDate: '1953-05-21',
    sex: 'FEMALE',
    address: '456 BROADWAY, SAN JUAN',
    status: 'Verified',
    isRegistered: true,
    houseNo: '456',
    street: 'BROADWAY',
    barangay: 'GREENHILLS',
    district: '2ND DISTRICT',
    city: 'SAN JUAN CITY',
    province: 'METRO MANILA'
  },
  {
    id: 'r3',
    type: 'LCR',
    firstName: 'EDDIE',
    lastName: 'GARCIA',
    middleName: 'P',
    birthDate: '1929-05-02',
    sex: 'MALE',
    address: '789 SUNSET BLVD, SAN JUAN',
    status: 'Verified',
    isRegistered: true,
    houseNo: '789',
    street: 'SUNSET BLVD',
    barangay: 'ISABELITA',
    district: '1ST DISTRICT',
    city: 'SAN JUAN CITY',
    province: 'METRO MANILA'
  }
];

export const INITIAL_ID_ISSUANCES: Application[] = [];
